#!/bin/bash 

red='\033[1;31m'
green='\033[1;32'
yellow='\033[0;33'
NC='\033[0m'

echo -e """ 

+---------------------------------------------------------------------------------+
|                            Author:- Techwebspot                                 |
+---------------------------------------------------------------------------------+
          ___ _         _      _          _      ___                  
         | _ ) |__ _ __| |__  /_\  _ _ __| |_   | _ \___ _ __  ___ ___
         | _ \ /  \` / _| / / / _ \| '_/ _| ' \  |   / -_) '_ \/ _ (_-<
         |___/_\__,_\__|_\_\/_/ \_\_| \__|_||_| |_|_\___| .__/\___/__/
                                                       |_|           
${red}
                                       -                                                   
                                      .o+                 
                                      ooo/                 
                                     +oooo:                                                                                  
                                    +oooooo:               
                                   -+oooooo+:              
                                  /:-:++oooo+:             
                                 /++++/+++++++:            
                                /++++++++++++++:           
                               /+++ooooooooooooo/         
                             ./ooosssso++osssssso+        
                            .oossssso-    /ossssss+       
                           -osssssso.      :ssssssso.      
                          :osssssss/        osssso+++.     
                         /ossssssss/        +ssssooo/-     
                        /ossssso+/:-        -:/+osssso+-   
                       +sso+:-                   .-/+oso:  
                      ++:.                            -/+/
                     .                                   / 
${NC} """


if [ $EUID != 0 ]
then
	echo "------------------------------------------------------------------------------------"
	echo "                       [-] Error: You must run as a root                            "
	echo "------------------------------------------------------------------------------------"
	exit 1
fi

echo -e "${green} [*] List of category of tools: ${NC}"

pacman -Sg | grep blackarch

echo -e "\n${red}[*] Enter the category of the tools which you want to install ${NC}"
echo -e "${red}Eg. Category: wireless ${NC}"

read -p "Category: " category

pacman -S blackarch-${category}
